### ISSUE TITLE
always change to google account login after reboot

### ISSUE THREAD

**Issue by firerflystar** [clipto-pro/Desktop#102]
i has registered two accounts, only one i really use it for now , and another i am not purpose to use is  a google account .
but it always change to google account after reboot computer , because i use chrome and there is login with google account. 

it dectected and login automaticlly . so i have to logout and change it back another.  

is there any method login with correct account i purpose to use everytime reboot computer ?  how to fix it ?

thanks for helping!

**Comment by atrashler** [comment]
1) Could you write the whole scenario please?

Technically it should not happen if you are authorized with any account and open the app after reboot.

2) Or could you try to sign in with “Shift” key (click on the Sign In button while holding the Shift). In this scenario the app will use its internal window to complete the flow instead of the default browser. So it will ignore the global cache and existing cookies.

**Comment by firerflystar** [comment]
update to 5.1.1 , problem fixed .
