### ISSUE TITLE
web version no sync

### ISSUE THREAD

**Issue by aluiziomachado** [clipto-pro/Desktop#23]
web version do not sync with android version
is there a delay for it ?

**Comment by atrashler** [comment]
No. It should not be a delay (just have checked). Please reopen the Android app or refresh a browser page.

**Comment by aluiziomachado** [comment]
Ok. reopening Android app or refreshing web doesnt work. Already tried logoff/login on webpage and  still doesnt work. 
It has already synced before (other day) , and the web version  contains some notes , but it doesnt change from now on after adding new notes on android app.
I´ll post if i have some delay for it
by the way.....great app !

**Comment by atrashler** [comment]
Hmm.. Questions:

1) where are you located? (Maybe in your country there is some problems with firebase services. But in such case the authorisation flow should also stop working)
2) what browser do you use?
3) have you tried to use another browser?
4) have you tried the same scenario by using one of our desktop clients?

The answers let me understand where the problem is (is it on the phone or in browser or somewhere else)

Thanks!

**Comment by aluiziomachado** [comment]
Im using Chrome but tried Edge and the same problem
BUT, when i logged off from android app and log in again it WORKED !
thanks !

**Comment by atrashler** [comment]
Strange behaviour. It should not work in such way. We will check it. Thanks!

**Comment by aluiziomachado** [comment]
thanks ! today i pay the coffee...keep going..the app is awesome !

**Comment by atrashler** [comment]
Thanks for your support!
