### ISSUE TITLE
Problem with login / no text display

### ISSUE THREAD

**Issue by RemiWest** [clipto-pro/Desktop#28]
Windows 10 pro x64_1909 / 18363.476
clean system installation, no possibility of logging into the synchronization account. 
![Adnotacja 2019-12-01 112029](https://user-images.githubusercontent.com/46202613/69913339-d86c7f00-1436-11ea-94f8-c236d52ebf44.jpg)
This applies to versions 1.4.4 and 1.6.0

**Comment by atrashler** [comment]
During the login flow the app uses “web-based” form. Please sure that the internet is available and wait until the page is loaded (it should take 1-15 seconds in average).

We will check it also. Thanka!

**Comment by atrashler** [comment]
Please check it. It should work now. No need to update desktop app. Thanks!

**Comment by RemiWest** [comment]
Now it is working !
![Adnotacja 2019-12-01 224459](https://user-images.githubusercontent.com/46202613/69920812-b3a2f680-148c-11ea-8849-2bffb78b99b7.jpg)

**Comment by fracama87** [comment]
I've the same problem by few days

**Comment by atrashler** [comment]
If you have updated to the latest version (2.4.6) please fully re-install the app. It has some internal changes that can cause such problem. 
The normal behavior of the app:
1) it does not have problems with authorization
2) it syncs data instantly with possible delay up to 30 seconds.

If one of this conditions is wrong than re-login to the app or fully re-install it.
If it does not help please contact me via email.

**Comment by fracama87** [comment]
I've tried anuthing for days all versions installing, cleaning, full re-install... anything! and now I've just closed and reopened and in some way it's working again.

**Comment by atrashler** [comment]
The only problem that can be that in the latest version (2.4.6) I applied a new internal identifier that can install another app instead of overwriting the previous one. So if you have previously installed app then the new one can be installed silently as another application and you could using the previous executable instead of the new one. It could be my fault because in the release notes I asked users to fully delete previous app before installing the new one.
Now please keep in mind that the app should not have problems with cloud more that for few minutes and text me if it is not true:)
